### ISSUE TITLE
Add V2 samples in docs for missing Triggers/bindings

### ISSUE THREAD

**Issue by pdthummar** [Azure/azure-functions-python-worker#1261]
Docs update needed for following triggers/bindings: 
Table
Warmup Trigger
SB Queue Output
```[tasklist]
### Tasks
- [ ] Retry Policy Examples for ProgModelv2
- [ ] WarmUp Trigger Examples for ProgModelv2
- [ ] Table Storage Trigger Examples for ProgModelv2
- [ ] SB Queue Output Binding Examples for ProgModelv2
- [ ] Dapr Examples for ProgModelv2 (to check with Dapr Team
```

**Comment by vrdmr** [comment]
EventGrid examples

**Comment by nvablaest** [comment]
Warmup Trigger example would be helpfull

**Comment by vrdmr** [comment]
![warmup_trigger](https://github.com/Azure/azure-functions-python-worker/assets/1047040/5bb4ca44-df62-4de8-bbf4-39281c94e77b)

**Comment by sudharsan2020** [comment]
@vrdmr Can you please suggest how can I add a warmup function for `Azure Functions V2 with Service Bus Trigger`. We are implementing a unified health check for all the Azure Functions.

I am expecting something like this:

![image](https://github.com/Azure/azure-functions-python-worker/assets/9370130/ddf9b5ba-3ee1-4eec-9d2a-aa8575b4e5cb)

**Comment by pdthummar** [comment]
@sudharsan2020 there may only be one warmup function per app. You can create a single warmup function as shown below, and then create separate functions for your service bus triggers. Thanks

```
import azure.functions as func
import logging

app = func.FunctionApp()


@app.warm_up_trigger('warmup')
def warmup(warmup) -> None:
    logging.info('Function App instance is warm')
    
```

**Comment by pdthummar** [comment]
@sudharsan2020  A warmup trigger is invoked when an instance is added to scale a running function app. The warmup trigger lets you define a function that's run when a new instance of your function app is started.  

For more info, please refer: [Azure Functions warmup trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process&pivots=programming-language-python) Thanks

**Comment by Marsharks** [comment]
> @sudharsan2020 there may only be one warmup function per app. You can create a single warmup function as shown below, and then create separate functions for your service bus triggers. Thanks
> 
> ```
> import azure.functions as func
> import logging
> 
> app = func.FunctionApp()
> 
> 
> @app.warm_up_trigger('warmup')
> def warmup(warmup) -> None:
>     logging.info('Function App instance is warm')
>     
> ```

When testing in Azure, I get System.NotImplementedException at Microsoft.Azure.WebJobs.Host.Bindings.TriggerAdapterBindingProvider`2+ExactBinding+<BindAsync>d__10.MoveNext
